"""team chat invite link

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 10:40:57.243188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_link', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_teams_chat_id'), ['chat_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teams_chat_id'), type_='unique')
        batch_op.drop_column('invite_link')

    # ### end Alembic commands ###
