"""daily marks

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 14:47:50.052922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tactic_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['weekly_tactics.id'], name=op.f('fk_daily_marks_tactic_id_weekly_tactics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_marks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_marks')),
    sa.UniqueConstraint('tactic_id', 'day', name=op.f('uq_daily_marks_tactic_id_day'))
    )
    with op.batch_alter_table('daily_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_marks_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_marks_tactic_id'), ['tactic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_marks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_marks_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_marks_tactic_id'))
        batch_op.drop_index(batch_op.f('ix_daily_marks_day'))

    op.drop_table('daily_marks')
    # ### end Alembic commands ###
