"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 10:29:56.386878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('onboarding_step', sa.Enum('WHEEL', 'EXPLORE', 'ELIMINATE', 'INTENT', 'TACTICS', 'DONE', name='onboardingstep', native_enum=False), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('send_report', sa.Enum('TEAM', 'ADMIN', 'NONE', name='reporttarget', native_enum=False), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=True),
    sa.Column('onboarding_position', sa.Integer(), nullable=True),
    sa.Column('last_reported_week', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('explore_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_explore_list_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explore_list'))
    )
    with op.batch_alter_table('explore_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explore_list_user_id'), ['user_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('user_id', name=op.f('uq_team_members_user_id'))
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    op.create_table('wheel_of_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wheel_of_balance_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wheel_of_balance')),
    sa.UniqueConstraint('user_id', 'cycle', 'sphere', name=op.f('uq_wheel_of_balance_user_id_cycle_sphere'))
    )
    with op.batch_alter_table('wheel_of_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_of_balance_user_id'), ['user_id'], unique=False)

    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('explore_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['explore_item_id'], ['explore_list.id'], name=op.f('fk_priorities_explore_item_id_explore_list'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_priorities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priorities')),
    sa.UniqueConstraint('user_id', 'cycle', 'position', name=op.f('uq_priorities_user_id_cycle_position'))
    )
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priorities_user_id'), ['user_id'], unique=False)

    op.create_table('essential_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], name=op.f('fk_essential_intent_priority_id_priorities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essential_intent')),
    sa.UniqueConstraint('priority_id', name=op.f('uq_essential_intent_priority_id'))
    )
    op.create_table('weekly_tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], name=op.f('fk_weekly_tactics_priority_id_priorities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_tactics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_tactics'))
    )
    with op.batch_alter_table('weekly_tactics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_tactics_priority_id'), ['priority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_tactics_user_id'), ['user_id'], unique=False)

    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tactic_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['weekly_tactics.id'], name=op.f('fk_checkins_tactic_id_weekly_tactics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    sa.UniqueConstraint('tactic_id', 'week_start', name=op.f('uq_checkins_tactic_id_week_start'))
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_tactic_id'), ['tactic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkins_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkins_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_week_start'))
        batch_op.drop_index(batch_op.f('ix_checkins_user_id'))
        batch_op.drop_index(batch_op.f('ix_checkins_tactic_id'))

    op.drop_table('checkins')
    with op.batch_alter_table('weekly_tactics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_tactics_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_tactics_priority_id'))

    op.drop_table('weekly_tactics')
    op.drop_table('essential_intent')
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorities_user_id'))

    op.drop_table('priorities')
    with op.batch_alter_table('wheel_of_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_of_balance_user_id'))

    op.drop_table('wheel_of_balance')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('explore_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explore_list_user_id'))

    op.drop_table('explore_list')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
