"""tactic weeks

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 13:06:48.558174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_tactics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weeks', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_tactics', schema=None) as batch_op:
        batch_op.drop_column('weeks')

    # ### end Alembic commands ###
